services:
  - type: web
    name: SergioMedina
    env: node
    buildCommand: npm install
    startCommand: node server
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 14
    build:
      packages:
        - libssl-dev
        - libfontconfig1
        - libx11-dev
        - libx11-xcb-dev
        - libxcb1-dev
        - libxcomposite-dev
        - libxcursor-dev
        - libxdamage-dev
        - libxi-dev
        - libxtst-dev
        - libnss3
        - libxrandr-dev
        - libasound2
        - libatk1.0-0
        - libatk-bridge2.0-0
        - libcups2
        - libdbus-1-3
        - libgdk-pixbuf2.0-0
        - libgconf-2-4
        - libgtk-3-0
        - libnspr4
        - libxss1
        - libx11-xcb1
        - libxcb-dri3-0

